{
 "title": "Clicklearn Detections",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Buoys online",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 1) by (job)" }
   ]
  },
  {
   "title": "Total Detections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"clicklearn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upcall\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"file_name\"] != \"myfile\")\r\n  |> group(columns: [\"score\"])"
    }
   ]
  },
  {
   "title": "Detections last 12hrs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"clicklearn\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upcall\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"file_name\"] != \"myfile\")\r\n  |> group(columns: [\"score\"])"
    }
   ]
  },
  {
   "title": "Map Distribution - COMING SOON",
   "type": "geomap",
   "description": "Grafana Geomap is still in Beta and is not fully working with latest version of InfluxDB's FLUX query language. Support is expected soon in one of the next releases",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"clicklearn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upcall_test7\")"
    }
   ]
  },
  {
   "title": "Score Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"clicklearn\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"upcall\" and\r\n    r._field == \"score\" and\r\n    r.file_name != \"myfile\"\r\n  )"
    }
   ]
  },
  {
   "title": "Detection Scores",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"clicklearn\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"upcall\" and\r\n    r._field == \"score\" and\r\n    r.file_name != \"myfile\"\r\n  )"
    }
   ]
  }
 ]
}